/*************************************************************/
/*                                                           */
/* Copyright (C) 2011 Weil Cornell Medical College           */
/*                                                           */
/*  Author: Pascal Spincemaille                              */
/*                                                           */
/*************************************************************/
#ifndef _BRSFC_CV_ZPRINTER_H_
#define _BRSFC_CV_ZPRINTER_H_
#ifdef __cplusplus
extern "C" {
#endif
#include "brsfc_cv.h"
#include "zlib.h"
void zprint_brsfc_int(gzFile fp, char *str, int indent, int * val, int n);
void zprint_brsfc_int32_t(gzFile fp, char *str, int indent, int32_t * val, int n);
void zprint_brsfc_unsigned_char(gzFile fp, char *str, int indent, unsigned char * val, int n);
void zprint_brsfc_signed_char(gzFile fp, char *str, int indent, signed char * val, int n);
void zprint_brsfc_n32(gzFile fp, char *str, int indent, n32 * val, int n);
void zprint_brsfc_s32(gzFile fp, char *str, int indent, s32 * val, int n);
void zprint_brsfc_double(gzFile fp, char *str, int indent, double * val, int n);
void zprint_brsfc_short(gzFile fp, char *str, int indent, short * val, int n);
void zprint_brsfc_float(gzFile fp, char *str, int indent, float * val, int n);
void zprint_brsfc_long(gzFile fp, char *str, int indent, long * val, int n);
void zprint_brsfc_unsigned_long_int(gzFile fp, char *str, int indent, unsigned long int * val, int n);
void zprint_brsfc_u_int64_t(gzFile fp, char *str, int indent, u_int64_t * val, int n);
void zprint_brsfc_int64_t(gzFile fp, char *str, int indent, int64_t * val, int n);
void zprint_brsfc_unsigned_short(gzFile fp, char *str, int indent, unsigned short * val, int n);
void zprint_brsfc_unsigned_long(gzFile fp, char *str, int indent, unsigned long * val, int n);
void zprint_brsfc_long_int(gzFile fp, char *str, int indent, long int * val, int n);
void zprint_brsfc_unsigned_int(gzFile fp, char *str, int indent, unsigned int * val, int n);
void zprint_brsfc_int16_t(gzFile fp, char *str, int indent, int16_t * val, int n);
void zprint_brsfc_unsigned_short_int(gzFile fp, char *str, int indent, unsigned short int * val, int n);
void zprint_brsfc_u_int16_t(gzFile fp, char *str, int indent, u_int16_t * val, int n);
void zprint_brsfc_char(gzFile fp, char *str, int indent, char * val, int n);
void zprint_brsfc_signed_short_int(gzFile fp, char *str, int indent, signed short int * val, int n);
void zprint_brsfc_u_int32_t(gzFile fp, char *str, int indent, u_int32_t * val, int n);
void zprint_brsfc_short_int(gzFile fp, char *str, int indent, short int * val, int n);
void zprint_brsfc_signed_int(gzFile fp, char *str, int indent, signed int * val, int n);
void zprint_brsfc_ptrdiff_t(gzFile fp, char *str, int indent, ptrdiff_t * val, int n);
void zprint_brsfc_size_t(gzFile fp, char *str, int indent, size_t * val, int n);
void zprint_brsfc_wchar_t(gzFile fp, char *str, int indent, wchar_t * val, int n);
void zprint_brsfc_int8_t(gzFile fp, char *str, int indent, int8_t * val, int n);
void zprint_brsfc_uint8_t(gzFile fp, char *str, int indent, uint8_t * val, int n);
void zprint_brsfc_uint16_t(gzFile fp, char *str, int indent, uint16_t * val, int n);
void zprint_brsfc_uint32_t(gzFile fp, char *str, int indent, uint32_t * val, int n);
void zprint_brsfc_uint64_t(gzFile fp, char *str, int indent, uint64_t * val, int n);
void zprint_brsfc_int_least8_t(gzFile fp, char *str, int indent, int_least8_t * val, int n);
void zprint_brsfc_int_least16_t(gzFile fp, char *str, int indent, int_least16_t * val, int n);
void zprint_brsfc_int_least32_t(gzFile fp, char *str, int indent, int_least32_t * val, int n);
void zprint_brsfc_int_least64_t(gzFile fp, char *str, int indent, int_least64_t * val, int n);
void zprint_brsfc_uint_least8_t(gzFile fp, char *str, int indent, uint_least8_t * val, int n);
void zprint_brsfc_uint_least16_t(gzFile fp, char *str, int indent, uint_least16_t * val, int n);
void zprint_brsfc_uint_least32_t(gzFile fp, char *str, int indent, uint_least32_t * val, int n);
void zprint_brsfc_uint_least64_t(gzFile fp, char *str, int indent, uint_least64_t * val, int n);
void zprint_brsfc_int_fast8_t(gzFile fp, char *str, int indent, int_fast8_t * val, int n);
void zprint_brsfc_int_fast16_t(gzFile fp, char *str, int indent, int_fast16_t * val, int n);
void zprint_brsfc_int_fast32_t(gzFile fp, char *str, int indent, int_fast32_t * val, int n);
void zprint_brsfc_int_fast64_t(gzFile fp, char *str, int indent, int_fast64_t * val, int n);
void zprint_brsfc_uint_fast8_t(gzFile fp, char *str, int indent, uint_fast8_t * val, int n);
void zprint_brsfc_uint_fast16_t(gzFile fp, char *str, int indent, uint_fast16_t * val, int n);
void zprint_brsfc_uint_fast32_t(gzFile fp, char *str, int indent, uint_fast32_t * val, int n);
void zprint_brsfc_uint_fast64_t(gzFile fp, char *str, int indent, uint_fast64_t * val, int n);
void zprint_brsfc_intptr_t(gzFile fp, char *str, int indent, intptr_t * val, int n);
void zprint_brsfc_uintptr_t(gzFile fp, char *str, int indent, uintptr_t * val, int n);
void zprint_brsfc_intmax_t(gzFile fp, char *str, int indent, intmax_t * val, int n);
void zprint_brsfc_uintmax_t(gzFile fp, char *str, int indent, uintmax_t * val, int n);
void zprint_brsfc_s8(gzFile fp, char *str, int indent, s8 * val, int n);
void zprint_brsfc_n8(gzFile fp, char *str, int indent, n8 * val, int n);
void zprint_brsfc_s16(gzFile fp, char *str, int indent, s16 * val, int n);
void zprint_brsfc_n16(gzFile fp, char *str, int indent, n16 * val, int n);
void zprint_brsfc_s64(gzFile fp, char *str, int indent, s64 * val, int n);
void zprint_brsfc_n64(gzFile fp, char *str, int indent, n64 * val, int n);
void zprint_brsfc_f32(gzFile fp, char *str, int indent, f32 * val, int n);
void zprint_brsfc_f64(gzFile fp, char *str, int indent, f64 * val, int n);
void zprint_brsfc_ulong(gzFile fp, char *str, int indent, ulong * val, int n);
void zprint_brsfc_ushort(gzFile fp, char *str, int indent, ushort * val, int n);
void zprint_brsfc_uint(gzFile fp, char *str, int indent, uint * val, int n);
void zprint_brsfc_struct_timespec(gzFile fp, char *str, int indent, struct timespec * val, int n);
void zprint_brsfc_power_monitor_table_t(gzFile fp, char *str, int indent, power_monitor_table_t * val, int n);
void zprint_brsfc_entry_point_table_t(gzFile fp, char *str, int indent, entry_point_table_t * val, int n);
void zprint_brsfc_ENTRY_POINT_TABLE(gzFile fp, char *str, int indent, ENTRY_POINT_TABLE * val, int n);
void zprint_brsfc_ENTRY_PNT_TABLE(gzFile fp, char *str, int indent, ENTRY_PNT_TABLE * val, int n);
void zprint_brsfc_CHAR(gzFile fp, char *str, int indent, CHAR * val, int n);
void zprint_brsfc_SHORT(gzFile fp, char *str, int indent, SHORT * val, int n);
void zprint_brsfc_INT(gzFile fp, char *str, int indent, INT * val, int n);
void zprint_brsfc_LONG(gzFile fp, char *str, int indent, LONG * val, int n);
void zprint_brsfc_FLOAT(gzFile fp, char *str, int indent, FLOAT * val, int n);
void zprint_brsfc_DOUBLE(gzFile fp, char *str, int indent, DOUBLE * val, int n);
void zprint_brsfc_UCHAR(gzFile fp, char *str, int indent, UCHAR * val, int n);
void zprint_brsfc_USHORT(gzFile fp, char *str, int indent, USHORT * val, int n);
void zprint_brsfc_UINT(gzFile fp, char *str, int indent, UINT * val, int n);
void zprint_brsfc_ULONG(gzFile fp, char *str, int indent, ULONG * val, int n);
void zprint_brsfc_STATUS(gzFile fp, char *str, int indent, STATUS * val, int n);
void zprint_brsfc_t_axis(gzFile fp, char *str, int indent, t_axis * val, int n);
void zprint_brsfc_t_fopen_mode(gzFile fp, char *str, int indent, t_fopen_mode * val, int n);
void zprint_brsfc__G_fpos64_t(gzFile fp, char *str, int indent, _G_fpos64_t * val, int n);
void zprint_brsfc_struct__IO_marker(gzFile fp, char *str, int indent, struct _IO_marker  * val, int n);
void zprint_brsfc_datavalue(gzFile fp, char *str, int indent, datavalue * val, int n);
void zprint_brsfc_GRADIENT_COIL_E(gzFile fp, char *str, int indent, GRADIENT_COIL_E * val, int n);
void zprint_brsfc_PSD_BOARD_TYPE_E(gzFile fp, char *str, int indent, PSD_BOARD_TYPE_E * val, int n);
void zprint_brsfc_GRADIENT_COIL_METHOD_E(gzFile fp, char *str, int indent, GRADIENT_COIL_METHOD_E * val, int n);
void zprint_brsfc_POWER_IN_HEAT_CALC_E(gzFile fp, char *str, int indent, POWER_IN_HEAT_CALC_E * val, int n);
void zprint_brsfc_WF_HARDWARE_TYPE(gzFile fp, char *str, int indent, WF_HARDWARE_TYPE * val, int n);
void zprint_brsfc_HW_DIRECTION(gzFile fp, char *str, int indent, HW_DIRECTION * val, int n);
void zprint_brsfc_SSP_S_ATTRIB(gzFile fp, char *str, int indent, SSP_S_ATTRIB * val, int n);
void zprint_brsfc_TYPDAB_PACKETS(gzFile fp, char *str, int indent, TYPDAB_PACKETS * val, int n);
void zprint_brsfc_TYPACQ_PASS(gzFile fp, char *str, int indent, TYPACQ_PASS * val, int n);
void zprint_brsfc_WF_PROCESSOR(gzFile fp, char *str, int indent, WF_PROCESSOR * val, int n);
void zprint_brsfc_WF_HW_WAVEFORM_PTR(gzFile fp, char *str, int indent, WF_HW_WAVEFORM_PTR * val, int n);
void zprint_brsfc_WF_HW_INSTR_PTR(gzFile fp, char *str, int indent, WF_HW_INSTR_PTR * val, int n);
void zprint_brsfc_WF_INSTR_HDR(gzFile fp, char *str, int indent, WF_INSTR_HDR * val, int n);
void zprint_brsfc_CONST_EXT(gzFile fp, char *str, int indent, CONST_EXT * val, int n);
void zprint_brsfc_HADAMARD_EXT(gzFile fp, char *str, int indent, HADAMARD_EXT * val, int n);
void zprint_brsfc_RAMP_EXT(gzFile fp, char *str, int indent, RAMP_EXT * val, int n);
void zprint_brsfc_SINC_EXT(gzFile fp, char *str, int indent, SINC_EXT * val, int n);
void zprint_brsfc_SINUSOID_EXT(gzFile fp, char *str, int indent, SINUSOID_EXT * val, int n);
void zprint_brsfc_WF_PULSE_EXT(gzFile fp, char *str, int indent, WF_PULSE_EXT * val, int n);
void zprint_brsfc_WF_PULSE_TYPES(gzFile fp, char *str, int indent, WF_PULSE_TYPES * val, int n);
void zprint_brsfc_WF_PGMTAG(gzFile fp, char *str, int indent, WF_PGMTAG * val, int n);
void zprint_brsfc_WF_PGMREUSE(gzFile fp, char *str, int indent, WF_PGMREUSE * val, int n);
void zprint_brsfc_WF_PULSE(gzFile fp, char *str, int indent, WF_PULSE * val, int n);
void zprint_brsfc_WF_INSTR_QUEUE(gzFile fp, char *str, int indent, WF_INSTR_QUEUE * val, int n);
void zprint_brsfc_SEQUENCE_ENTRIES(gzFile fp, char *str, int indent, SEQUENCE_ENTRIES * val, int n);
void zprint_brsfc_SEQUENCE_LIST(gzFile fp, char *str, int indent, SEQUENCE_LIST * val, int n);
void zprint_brsfc_exciterSelection(gzFile fp, char *str, int indent, exciterSelection * val, int n);
void zprint_brsfc_receiverSelection(gzFile fp, char *str, int indent, receiverSelection * val, int n);
void zprint_brsfc_demodSelection(gzFile fp, char *str, int indent, demodSelection * val, int n);
void zprint_brsfc_navSelection(gzFile fp, char *str, int indent, navSelection * val, int n);
void zprint_brsfc_struct_EXT_CERD_PARAMS(gzFile fp, char *str, int indent, struct EXT_CERD_PARAMS * val, int n);
void zprint_brsfc_PSD_FILTER_GEN(gzFile fp, char *str, int indent, PSD_FILTER_GEN * val, int n);
void zprint_brsfc_SCAN_INFO(gzFile fp, char *str, int indent, SCAN_INFO * val, int n);
void zprint_brsfc_PSC_INFO(gzFile fp, char *str, int indent, PSC_INFO * val, int n);
void zprint_brsfc_DATA_ACQ_ORDER(gzFile fp, char *str, int indent, DATA_ACQ_ORDER * val, int n);
void zprint_brsfc_RSP_INFO(gzFile fp, char *str, int indent, RSP_INFO * val, int n);
void zprint_brsfc_CTMEntryType(gzFile fp, char *str, int indent, CTMEntryType * val, int n);
void zprint_brsfc_QuadVolWeightType(gzFile fp, char *str, int indent, QuadVolWeightType * val, int n);
void zprint_brsfc_ChannelTransTableEntryType(gzFile fp, char *str, int indent, ChannelTransTableEntryType * val, int n);
void zprint_brsfc_INSTALL_COIL_INFO(gzFile fp, char *str, int indent, INSTALL_COIL_INFO * val, int n);
void zprint_brsfc_INSTALL_COIL_CONNECTOR_INFO(gzFile fp, char *str, int indent, INSTALL_COIL_CONNECTOR_INFO * val, int n);
void zprint_brsfc_COIL_CONFIG_PARAM_TYPE(gzFile fp, char *str, int indent, COIL_CONFIG_PARAM_TYPE * val, int n);
void zprint_brsfc_APPLICATION_CONFIG_PARAM_TYPE(gzFile fp, char *str, int indent, APPLICATION_CONFIG_PARAM_TYPE * val, int n);
void zprint_brsfc_APPLICATION_CONFIG_HDR(gzFile fp, char *str, int indent, APPLICATION_CONFIG_HDR * val, int n);
void zprint_brsfc_COIL_INFO(gzFile fp, char *str, int indent, COIL_INFO * val, int n);
void zprint_brsfc_TX_COIL_INFO(gzFile fp, char *str, int indent, TX_COIL_INFO * val, int n);
void zprint_brsfc_PSD_COIL_INFO(gzFile fp, char *str, int indent, PSD_COIL_INFO * val, int n);
void zprint_brsfc_GRAD_PULSE(gzFile fp, char *str, int indent, GRAD_PULSE * val, int n);
void zprint_brsfc_RF_PULSE(gzFile fp, char *str, int indent, RF_PULSE * val, int n);
void zprint_brsfc_RF_PULSE_INFO(gzFile fp, char *str, int indent, RF_PULSE_INFO * val, int n);
void zprint_brsfc_PHYS_GRAD(gzFile fp, char *str, int indent, PHYS_GRAD * val, int n);
void zprint_brsfc_t_xact(gzFile fp, char *str, int indent, t_xact * val, int n);
void zprint_brsfc_t_yact(gzFile fp, char *str, int indent, t_yact * val, int n);
void zprint_brsfc_t_zact(gzFile fp, char *str, int indent, t_zact * val, int n);
void zprint_brsfc_ramp_t(gzFile fp, char *str, int indent, ramp_t * val, int n);
void zprint_brsfc_LOG_GRAD(gzFile fp, char *str, int indent, LOG_GRAD * val, int n);
void zprint_brsfc_OPT_GRAD_INPUT(gzFile fp, char *str, int indent, OPT_GRAD_INPUT * val, int n);
void zprint_brsfc_OPT_GRAD_PARAMS(gzFile fp, char *str, int indent, OPT_GRAD_PARAMS * val, int n);
void zprint_brsfc_dbkey_exam_type(gzFile fp, char *str, int indent, dbkey_exam_type * val, int n);
void zprint_brsfc_dbkey_magic_type(gzFile fp, char *str, int indent, dbkey_magic_type * val, int n);
void zprint_brsfc_dbkey_series_type(gzFile fp, char *str, int indent, dbkey_series_type * val, int n);
void zprint_brsfc_dbkey_image_type(gzFile fp, char *str, int indent, dbkey_image_type * val, int n);
void zprint_brsfc_DbKey(gzFile fp, char *str, int indent, DbKey * val, int n);
void zprint_brsfc_OP_NMRID_TYPE(gzFile fp, char *str, int indent, OP_NMRID_TYPE * val, int n);
void zprint_brsfc_OP_HDR1_TYPE(gzFile fp, char *str, int indent, OP_HDR1_TYPE * val, int n);
void zprint_brsfc_OP_HDR_TYPE(gzFile fp, char *str, int indent, OP_HDR_TYPE * val, int n);
void zprint_brsfc_OP_RECN_READY_TYPE(gzFile fp, char *str, int indent, OP_RECN_READY_TYPE * val, int n);
void zprint_brsfc_OP_RECN_READY_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_READY_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_FOO_TYPE(gzFile fp, char *str, int indent, OP_RECN_FOO_TYPE * val, int n);
void zprint_brsfc_OP_RECN_FOO_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_FOO_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_START_TYPE(gzFile fp, char *str, int indent, OP_RECN_START_TYPE * val, int n);
void zprint_brsfc_OP_RECN_START_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_START_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SCAN_STOPPED_TYPE(gzFile fp, char *str, int indent, OP_RECN_SCAN_STOPPED_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SCAN_STOPPED_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_SCAN_STOPPED_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_STOP_TYPE(gzFile fp, char *str, int indent, OP_RECN_STOP_TYPE * val, int n);
void zprint_brsfc_OP_RECN_STOP_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_STOP_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_IM_ALLOC_TYPE(gzFile fp, char *str, int indent, OP_RECN_IM_ALLOC_TYPE * val, int n);
void zprint_brsfc_OP_RECN_IM_ALLOC_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_IM_ALLOC_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SCAN_STARTED_TYPE(gzFile fp, char *str, int indent, OP_RECN_SCAN_STARTED_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SCAN_STARTED_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_SCAN_STARTED_PACK_TYPE * val, int n);
void zprint_brsfc_OP_VIEWTABLE_UPDATE_TYPE(gzFile fp, char *str, int indent, OP_VIEWTABLE_UPDATE_TYPE * val, int n);
void zprint_brsfc_OP_VIEWTABLE_UPDATE_PACK_TYPE(gzFile fp, char *str, int indent, OP_VIEWTABLE_UPDATE_PACK_TYPE * val, int n);
void zprint_brsfc_MROR_ADDR_BLOCK(gzFile fp, char *str, int indent, MROR_ADDR_BLOCK * val, int n);
void zprint_brsfc_MROR_ADDR_BLOCK_PKT(gzFile fp, char *str, int indent, MROR_ADDR_BLOCK_PKT * val, int n);
void zprint_brsfc_MROR_RETRIEVAL_DONE_TYPE(gzFile fp, char *str, int indent, MROR_RETRIEVAL_DONE_TYPE * val, int n);
void zprint_brsfc_SCAN_CALIB_INFO_TYPE(gzFile fp, char *str, int indent, SCAN_CALIB_INFO_TYPE * val, int n);
void zprint_brsfc_SCAN_CALIB_INFO_PACK_TYPE(gzFile fp, char *str, int indent, SCAN_CALIB_INFO_PACK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SIZE_CHECK_TYPE(gzFile fp, char *str, int indent, OP_RECN_SIZE_CHECK_TYPE * val, int n);
void zprint_brsfc_OP_RECN_SIZE_CHECK_PACK_TYPE(gzFile fp, char *str, int indent, OP_RECN_SIZE_CHECK_PACK_TYPE * val, int n);
void zprint_brsfc_EXAM_SCAN_DONE_TYPE(gzFile fp, char *str, int indent, EXAM_SCAN_DONE_TYPE * val, int n);
void zprint_brsfc_EXAM_SCAN_DONE_PACK_TYPE(gzFile fp, char *str, int indent, EXAM_SCAN_DONE_PACK_TYPE * val, int n);
void zprint_brsfc_POSITION_DETECTION_DONE_TYPE(gzFile fp, char *str, int indent, POSITION_DETECTION_DONE_TYPE * val, int n);
void zprint_brsfc_POSITION_DETECTION_DONE_PACK_TYPE(gzFile fp, char *str, int indent, POSITION_DETECTION_DONE_PACK_TYPE * val, int n);
void zprint_brsfc_CARDIAC_GATE_TYPE_E(gzFile fp, char *str, int indent, CARDIAC_GATE_TYPE_E * val, int n);
void zprint_brsfc_EXTERN_FILENAME(gzFile fp, char *str, int indent, EXTERN_FILENAME * val, int n);
void zprint_brsfc_PHASE_OFF(gzFile fp, char *str, int indent, PHASE_OFF * val, int n);
void zprint_brsfc_RSP_PSC_INFO(gzFile fp, char *str, int indent, RSP_PSC_INFO * val, int n);
void zprint_brsfc_GIR_INFO(gzFile fp, char *str, int indent, GIR_INFO * val, int n);
void zprint_brsfc_ZY_EXPORT(gzFile fp, char *str, int indent, ZY_EXPORT * val, int n);
void zprint_brsfc_VIEWORDER_MODE_E(gzFile fp, char *str, int indent, VIEWORDER_MODE_E * val, int n);
void zprint_brsfc_REG_VIEWORDER_MODE_E(gzFile fp, char *str, int indent, REG_VIEWORDER_MODE_E * val, int n);
void zprint_brsfc_REGION_ORDER_MODE_E(gzFile fp, char *str, int indent, REGION_ORDER_MODE_E * val, int n);
void zprint_brsfc_CAL_PARAM(gzFile fp, char *str, int indent, CAL_PARAM * val, int n);
void zprint_brsfc_PARAM4D(gzFile fp, char *str, int indent, PARAM4D * val, int n);
void zprint_brsfc_SPIRAL_VIEW(gzFile fp, char *str, int indent, SPIRAL_VIEW * val, int n);
void zprint_brsfc_SLAB_OFF(gzFile fp, char *str, int indent, SLAB_OFF * val, int n);
void zprint_brsfc_CYLR_RF_TYPE_E(gzFile fp, char *str, int indent, CYLR_RF_TYPE_E * val, int n);
void zprint_brsfc_t_ktsamp(gzFile fp, char *str, int indent, t_ktsamp * val, int n);
void zprint_brsfc_ViewTable_kyz(gzFile fp, char *str, int indent, ViewTable_kyz * val, int n);
void zprint_brsfc_t_cgatetype(gzFile fp, char *str, int indent, t_cgatetype * val, int n);
void zprint_brsfc_t_fcineim(gzFile fp, char *str, int indent, t_fcineim * val, int n);
void zprint_brsfc_t_fcinent(gzFile fp, char *str, int indent, t_fcinent * val, int n);
void zprint_brsfc_cv_type(gzFile fp, char *str, int indent, cv_type * val, int n);
#ifdef __cplusplus
}
#endif

#endif
