/*************************************************************/
/*                                                           */
/* Copyright (C) 2011 Weil Cornell Medical College           */
/*                                                           */
/*  Author: Pascal Spincemaille                              */
/*                                                           */
/*************************************************************/
#ifndef _BRSFC_CV_PRINTER_H_
#define _BRSFC_CV_PRINTER_H_
#ifdef __cplusplus
extern "C" {
#endif
#include "brsfc_cv.h"
void print_brsfc_int(FILE * fp, char *str, int indent, int * val, int n);
void print_brsfc_int32_t(FILE * fp, char *str, int indent, int32_t * val, int n);
void print_brsfc_unsigned_char(FILE * fp, char *str, int indent, unsigned char * val, int n);
void print_brsfc_signed_char(FILE * fp, char *str, int indent, signed char * val, int n);
void print_brsfc_n32(FILE * fp, char *str, int indent, n32 * val, int n);
void print_brsfc_s32(FILE * fp, char *str, int indent, s32 * val, int n);
void print_brsfc_double(FILE * fp, char *str, int indent, double * val, int n);
void print_brsfc_short(FILE * fp, char *str, int indent, short * val, int n);
void print_brsfc_float(FILE * fp, char *str, int indent, float * val, int n);
void print_brsfc_long(FILE * fp, char *str, int indent, long * val, int n);
void print_brsfc_unsigned_long_int(FILE * fp, char *str, int indent, unsigned long int * val, int n);
void print_brsfc_u_int64_t(FILE * fp, char *str, int indent, u_int64_t * val, int n);
void print_brsfc_int64_t(FILE * fp, char *str, int indent, int64_t * val, int n);
void print_brsfc_unsigned_short(FILE * fp, char *str, int indent, unsigned short * val, int n);
void print_brsfc_unsigned_long(FILE * fp, char *str, int indent, unsigned long * val, int n);
void print_brsfc_long_int(FILE * fp, char *str, int indent, long int * val, int n);
void print_brsfc_unsigned_int(FILE * fp, char *str, int indent, unsigned int * val, int n);
void print_brsfc_int16_t(FILE * fp, char *str, int indent, int16_t * val, int n);
void print_brsfc_unsigned_short_int(FILE * fp, char *str, int indent, unsigned short int * val, int n);
void print_brsfc_u_int16_t(FILE * fp, char *str, int indent, u_int16_t * val, int n);
void print_brsfc_char(FILE * fp, char *str, int indent, char * val, int n);
void print_brsfc_signed_short_int(FILE * fp, char *str, int indent, signed short int * val, int n);
void print_brsfc_u_int32_t(FILE * fp, char *str, int indent, u_int32_t * val, int n);
void print_brsfc_short_int(FILE * fp, char *str, int indent, short int * val, int n);
void print_brsfc_signed_int(FILE * fp, char *str, int indent, signed int * val, int n);
void print_brsfc_ptrdiff_t(FILE * fp, char *str, int indent, ptrdiff_t * val, int n);
void print_brsfc_size_t(FILE * fp, char *str, int indent, size_t * val, int n);
void print_brsfc_wchar_t(FILE * fp, char *str, int indent, wchar_t * val, int n);
void print_brsfc_int8_t(FILE * fp, char *str, int indent, int8_t * val, int n);
void print_brsfc_uint8_t(FILE * fp, char *str, int indent, uint8_t * val, int n);
void print_brsfc_uint16_t(FILE * fp, char *str, int indent, uint16_t * val, int n);
void print_brsfc_uint32_t(FILE * fp, char *str, int indent, uint32_t * val, int n);
void print_brsfc_uint64_t(FILE * fp, char *str, int indent, uint64_t * val, int n);
void print_brsfc_int_least8_t(FILE * fp, char *str, int indent, int_least8_t * val, int n);
void print_brsfc_int_least16_t(FILE * fp, char *str, int indent, int_least16_t * val, int n);
void print_brsfc_int_least32_t(FILE * fp, char *str, int indent, int_least32_t * val, int n);
void print_brsfc_int_least64_t(FILE * fp, char *str, int indent, int_least64_t * val, int n);
void print_brsfc_uint_least8_t(FILE * fp, char *str, int indent, uint_least8_t * val, int n);
void print_brsfc_uint_least16_t(FILE * fp, char *str, int indent, uint_least16_t * val, int n);
void print_brsfc_uint_least32_t(FILE * fp, char *str, int indent, uint_least32_t * val, int n);
void print_brsfc_uint_least64_t(FILE * fp, char *str, int indent, uint_least64_t * val, int n);
void print_brsfc_int_fast8_t(FILE * fp, char *str, int indent, int_fast8_t * val, int n);
void print_brsfc_int_fast16_t(FILE * fp, char *str, int indent, int_fast16_t * val, int n);
void print_brsfc_int_fast32_t(FILE * fp, char *str, int indent, int_fast32_t * val, int n);
void print_brsfc_int_fast64_t(FILE * fp, char *str, int indent, int_fast64_t * val, int n);
void print_brsfc_uint_fast8_t(FILE * fp, char *str, int indent, uint_fast8_t * val, int n);
void print_brsfc_uint_fast16_t(FILE * fp, char *str, int indent, uint_fast16_t * val, int n);
void print_brsfc_uint_fast32_t(FILE * fp, char *str, int indent, uint_fast32_t * val, int n);
void print_brsfc_uint_fast64_t(FILE * fp, char *str, int indent, uint_fast64_t * val, int n);
void print_brsfc_intptr_t(FILE * fp, char *str, int indent, intptr_t * val, int n);
void print_brsfc_uintptr_t(FILE * fp, char *str, int indent, uintptr_t * val, int n);
void print_brsfc_intmax_t(FILE * fp, char *str, int indent, intmax_t * val, int n);
void print_brsfc_uintmax_t(FILE * fp, char *str, int indent, uintmax_t * val, int n);
void print_brsfc_s8(FILE * fp, char *str, int indent, s8 * val, int n);
void print_brsfc_n8(FILE * fp, char *str, int indent, n8 * val, int n);
void print_brsfc_s16(FILE * fp, char *str, int indent, s16 * val, int n);
void print_brsfc_n16(FILE * fp, char *str, int indent, n16 * val, int n);
void print_brsfc_s64(FILE * fp, char *str, int indent, s64 * val, int n);
void print_brsfc_n64(FILE * fp, char *str, int indent, n64 * val, int n);
void print_brsfc_f32(FILE * fp, char *str, int indent, f32 * val, int n);
void print_brsfc_f64(FILE * fp, char *str, int indent, f64 * val, int n);
void print_brsfc_ulong(FILE * fp, char *str, int indent, ulong * val, int n);
void print_brsfc_ushort(FILE * fp, char *str, int indent, ushort * val, int n);
void print_brsfc_uint(FILE * fp, char *str, int indent, uint * val, int n);
void print_brsfc_struct_timespec(FILE * fp, char *str, int indent, struct timespec * val, int n);
void print_brsfc_power_monitor_table_t(FILE * fp, char *str, int indent, power_monitor_table_t * val, int n);
void print_brsfc_entry_point_table_t(FILE * fp, char *str, int indent, entry_point_table_t * val, int n);
void print_brsfc_ENTRY_POINT_TABLE(FILE * fp, char *str, int indent, ENTRY_POINT_TABLE * val, int n);
void print_brsfc_ENTRY_PNT_TABLE(FILE * fp, char *str, int indent, ENTRY_PNT_TABLE * val, int n);
void print_brsfc_CHAR(FILE * fp, char *str, int indent, CHAR * val, int n);
void print_brsfc_SHORT(FILE * fp, char *str, int indent, SHORT * val, int n);
void print_brsfc_INT(FILE * fp, char *str, int indent, INT * val, int n);
void print_brsfc_LONG(FILE * fp, char *str, int indent, LONG * val, int n);
void print_brsfc_FLOAT(FILE * fp, char *str, int indent, FLOAT * val, int n);
void print_brsfc_DOUBLE(FILE * fp, char *str, int indent, DOUBLE * val, int n);
void print_brsfc_UCHAR(FILE * fp, char *str, int indent, UCHAR * val, int n);
void print_brsfc_USHORT(FILE * fp, char *str, int indent, USHORT * val, int n);
void print_brsfc_UINT(FILE * fp, char *str, int indent, UINT * val, int n);
void print_brsfc_ULONG(FILE * fp, char *str, int indent, ULONG * val, int n);
void print_brsfc_STATUS(FILE * fp, char *str, int indent, STATUS * val, int n);
void print_brsfc_t_axis(FILE * fp, char *str, int indent, t_axis * val, int n);
void print_brsfc_t_fopen_mode(FILE * fp, char *str, int indent, t_fopen_mode * val, int n);
void print_brsfc__G_fpos64_t(FILE * fp, char *str, int indent, _G_fpos64_t * val, int n);
void print_brsfc_struct__IO_marker(FILE * fp, char *str, int indent, struct _IO_marker  * val, int n);
void print_brsfc_datavalue(FILE * fp, char *str, int indent, datavalue * val, int n);
void print_brsfc_GRADIENT_COIL_E(FILE * fp, char *str, int indent, GRADIENT_COIL_E * val, int n);
void print_brsfc_PSD_BOARD_TYPE_E(FILE * fp, char *str, int indent, PSD_BOARD_TYPE_E * val, int n);
void print_brsfc_GRADIENT_COIL_METHOD_E(FILE * fp, char *str, int indent, GRADIENT_COIL_METHOD_E * val, int n);
void print_brsfc_POWER_IN_HEAT_CALC_E(FILE * fp, char *str, int indent, POWER_IN_HEAT_CALC_E * val, int n);
void print_brsfc_WF_HARDWARE_TYPE(FILE * fp, char *str, int indent, WF_HARDWARE_TYPE * val, int n);
void print_brsfc_HW_DIRECTION(FILE * fp, char *str, int indent, HW_DIRECTION * val, int n);
void print_brsfc_SSP_S_ATTRIB(FILE * fp, char *str, int indent, SSP_S_ATTRIB * val, int n);
void print_brsfc_TYPDAB_PACKETS(FILE * fp, char *str, int indent, TYPDAB_PACKETS * val, int n);
void print_brsfc_TYPACQ_PASS(FILE * fp, char *str, int indent, TYPACQ_PASS * val, int n);
void print_brsfc_WF_PROCESSOR(FILE * fp, char *str, int indent, WF_PROCESSOR * val, int n);
void print_brsfc_WF_HW_WAVEFORM_PTR(FILE * fp, char *str, int indent, WF_HW_WAVEFORM_PTR * val, int n);
void print_brsfc_WF_HW_INSTR_PTR(FILE * fp, char *str, int indent, WF_HW_INSTR_PTR * val, int n);
void print_brsfc_WF_INSTR_HDR(FILE * fp, char *str, int indent, WF_INSTR_HDR * val, int n);
void print_brsfc_CONST_EXT(FILE * fp, char *str, int indent, CONST_EXT * val, int n);
void print_brsfc_HADAMARD_EXT(FILE * fp, char *str, int indent, HADAMARD_EXT * val, int n);
void print_brsfc_RAMP_EXT(FILE * fp, char *str, int indent, RAMP_EXT * val, int n);
void print_brsfc_SINC_EXT(FILE * fp, char *str, int indent, SINC_EXT * val, int n);
void print_brsfc_SINUSOID_EXT(FILE * fp, char *str, int indent, SINUSOID_EXT * val, int n);
void print_brsfc_WF_PULSE_EXT(FILE * fp, char *str, int indent, WF_PULSE_EXT * val, int n);
void print_brsfc_WF_PULSE_TYPES(FILE * fp, char *str, int indent, WF_PULSE_TYPES * val, int n);
void print_brsfc_WF_PGMTAG(FILE * fp, char *str, int indent, WF_PGMTAG * val, int n);
void print_brsfc_WF_PGMREUSE(FILE * fp, char *str, int indent, WF_PGMREUSE * val, int n);
void print_brsfc_WF_PULSE(FILE * fp, char *str, int indent, WF_PULSE * val, int n);
void print_brsfc_WF_INSTR_QUEUE(FILE * fp, char *str, int indent, WF_INSTR_QUEUE * val, int n);
void print_brsfc_SEQUENCE_ENTRIES(FILE * fp, char *str, int indent, SEQUENCE_ENTRIES * val, int n);
void print_brsfc_SEQUENCE_LIST(FILE * fp, char *str, int indent, SEQUENCE_LIST * val, int n);
void print_brsfc_exciterSelection(FILE * fp, char *str, int indent, exciterSelection * val, int n);
void print_brsfc_receiverSelection(FILE * fp, char *str, int indent, receiverSelection * val, int n);
void print_brsfc_demodSelection(FILE * fp, char *str, int indent, demodSelection * val, int n);
void print_brsfc_navSelection(FILE * fp, char *str, int indent, navSelection * val, int n);
void print_brsfc_struct_EXT_CERD_PARAMS(FILE * fp, char *str, int indent, struct EXT_CERD_PARAMS * val, int n);
void print_brsfc_PSD_FILTER_GEN(FILE * fp, char *str, int indent, PSD_FILTER_GEN * val, int n);
void print_brsfc_SCAN_INFO(FILE * fp, char *str, int indent, SCAN_INFO * val, int n);
void print_brsfc_PSC_INFO(FILE * fp, char *str, int indent, PSC_INFO * val, int n);
void print_brsfc_DATA_ACQ_ORDER(FILE * fp, char *str, int indent, DATA_ACQ_ORDER * val, int n);
void print_brsfc_RSP_INFO(FILE * fp, char *str, int indent, RSP_INFO * val, int n);
void print_brsfc_CTMEntryType(FILE * fp, char *str, int indent, CTMEntryType * val, int n);
void print_brsfc_QuadVolWeightType(FILE * fp, char *str, int indent, QuadVolWeightType * val, int n);
void print_brsfc_ChannelTransTableEntryType(FILE * fp, char *str, int indent, ChannelTransTableEntryType * val, int n);
void print_brsfc_INSTALL_COIL_INFO(FILE * fp, char *str, int indent, INSTALL_COIL_INFO * val, int n);
void print_brsfc_INSTALL_COIL_CONNECTOR_INFO(FILE * fp, char *str, int indent, INSTALL_COIL_CONNECTOR_INFO * val, int n);
void print_brsfc_COIL_CONFIG_PARAM_TYPE(FILE * fp, char *str, int indent, COIL_CONFIG_PARAM_TYPE * val, int n);
void print_brsfc_APPLICATION_CONFIG_PARAM_TYPE(FILE * fp, char *str, int indent, APPLICATION_CONFIG_PARAM_TYPE * val, int n);
void print_brsfc_APPLICATION_CONFIG_HDR(FILE * fp, char *str, int indent, APPLICATION_CONFIG_HDR * val, int n);
void print_brsfc_COIL_INFO(FILE * fp, char *str, int indent, COIL_INFO * val, int n);
void print_brsfc_TX_COIL_INFO(FILE * fp, char *str, int indent, TX_COIL_INFO * val, int n);
void print_brsfc_PSD_COIL_INFO(FILE * fp, char *str, int indent, PSD_COIL_INFO * val, int n);
void print_brsfc_GRAD_PULSE(FILE * fp, char *str, int indent, GRAD_PULSE * val, int n);
void print_brsfc_RF_PULSE(FILE * fp, char *str, int indent, RF_PULSE * val, int n);
void print_brsfc_RF_PULSE_INFO(FILE * fp, char *str, int indent, RF_PULSE_INFO * val, int n);
void print_brsfc_PHYS_GRAD(FILE * fp, char *str, int indent, PHYS_GRAD * val, int n);
void print_brsfc_t_xact(FILE * fp, char *str, int indent, t_xact * val, int n);
void print_brsfc_t_yact(FILE * fp, char *str, int indent, t_yact * val, int n);
void print_brsfc_t_zact(FILE * fp, char *str, int indent, t_zact * val, int n);
void print_brsfc_ramp_t(FILE * fp, char *str, int indent, ramp_t * val, int n);
void print_brsfc_LOG_GRAD(FILE * fp, char *str, int indent, LOG_GRAD * val, int n);
void print_brsfc_OPT_GRAD_INPUT(FILE * fp, char *str, int indent, OPT_GRAD_INPUT * val, int n);
void print_brsfc_OPT_GRAD_PARAMS(FILE * fp, char *str, int indent, OPT_GRAD_PARAMS * val, int n);
void print_brsfc_dbkey_exam_type(FILE * fp, char *str, int indent, dbkey_exam_type * val, int n);
void print_brsfc_dbkey_magic_type(FILE * fp, char *str, int indent, dbkey_magic_type * val, int n);
void print_brsfc_dbkey_series_type(FILE * fp, char *str, int indent, dbkey_series_type * val, int n);
void print_brsfc_dbkey_image_type(FILE * fp, char *str, int indent, dbkey_image_type * val, int n);
void print_brsfc_DbKey(FILE * fp, char *str, int indent, DbKey * val, int n);
void print_brsfc_OP_NMRID_TYPE(FILE * fp, char *str, int indent, OP_NMRID_TYPE * val, int n);
void print_brsfc_OP_HDR1_TYPE(FILE * fp, char *str, int indent, OP_HDR1_TYPE * val, int n);
void print_brsfc_OP_HDR_TYPE(FILE * fp, char *str, int indent, OP_HDR_TYPE * val, int n);
void print_brsfc_OP_RECN_READY_TYPE(FILE * fp, char *str, int indent, OP_RECN_READY_TYPE * val, int n);
void print_brsfc_OP_RECN_READY_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_READY_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_FOO_TYPE(FILE * fp, char *str, int indent, OP_RECN_FOO_TYPE * val, int n);
void print_brsfc_OP_RECN_FOO_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_FOO_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_START_TYPE(FILE * fp, char *str, int indent, OP_RECN_START_TYPE * val, int n);
void print_brsfc_OP_RECN_START_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_START_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_SCAN_STOPPED_TYPE(FILE * fp, char *str, int indent, OP_RECN_SCAN_STOPPED_TYPE * val, int n);
void print_brsfc_OP_RECN_SCAN_STOPPED_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_SCAN_STOPPED_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_STOP_TYPE(FILE * fp, char *str, int indent, OP_RECN_STOP_TYPE * val, int n);
void print_brsfc_OP_RECN_STOP_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_STOP_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_IM_ALLOC_TYPE(FILE * fp, char *str, int indent, OP_RECN_IM_ALLOC_TYPE * val, int n);
void print_brsfc_OP_RECN_IM_ALLOC_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_IM_ALLOC_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_SCAN_STARTED_TYPE(FILE * fp, char *str, int indent, OP_RECN_SCAN_STARTED_TYPE * val, int n);
void print_brsfc_OP_RECN_SCAN_STARTED_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_SCAN_STARTED_PACK_TYPE * val, int n);
void print_brsfc_OP_VIEWTABLE_UPDATE_TYPE(FILE * fp, char *str, int indent, OP_VIEWTABLE_UPDATE_TYPE * val, int n);
void print_brsfc_OP_VIEWTABLE_UPDATE_PACK_TYPE(FILE * fp, char *str, int indent, OP_VIEWTABLE_UPDATE_PACK_TYPE * val, int n);
void print_brsfc_MROR_ADDR_BLOCK(FILE * fp, char *str, int indent, MROR_ADDR_BLOCK * val, int n);
void print_brsfc_MROR_ADDR_BLOCK_PKT(FILE * fp, char *str, int indent, MROR_ADDR_BLOCK_PKT * val, int n);
void print_brsfc_MROR_RETRIEVAL_DONE_TYPE(FILE * fp, char *str, int indent, MROR_RETRIEVAL_DONE_TYPE * val, int n);
void print_brsfc_SCAN_CALIB_INFO_TYPE(FILE * fp, char *str, int indent, SCAN_CALIB_INFO_TYPE * val, int n);
void print_brsfc_SCAN_CALIB_INFO_PACK_TYPE(FILE * fp, char *str, int indent, SCAN_CALIB_INFO_PACK_TYPE * val, int n);
void print_brsfc_OP_RECN_SIZE_CHECK_TYPE(FILE * fp, char *str, int indent, OP_RECN_SIZE_CHECK_TYPE * val, int n);
void print_brsfc_OP_RECN_SIZE_CHECK_PACK_TYPE(FILE * fp, char *str, int indent, OP_RECN_SIZE_CHECK_PACK_TYPE * val, int n);
void print_brsfc_EXAM_SCAN_DONE_TYPE(FILE * fp, char *str, int indent, EXAM_SCAN_DONE_TYPE * val, int n);
void print_brsfc_EXAM_SCAN_DONE_PACK_TYPE(FILE * fp, char *str, int indent, EXAM_SCAN_DONE_PACK_TYPE * val, int n);
void print_brsfc_POSITION_DETECTION_DONE_TYPE(FILE * fp, char *str, int indent, POSITION_DETECTION_DONE_TYPE * val, int n);
void print_brsfc_POSITION_DETECTION_DONE_PACK_TYPE(FILE * fp, char *str, int indent, POSITION_DETECTION_DONE_PACK_TYPE * val, int n);
void print_brsfc_CARDIAC_GATE_TYPE_E(FILE * fp, char *str, int indent, CARDIAC_GATE_TYPE_E * val, int n);
void print_brsfc_EXTERN_FILENAME(FILE * fp, char *str, int indent, EXTERN_FILENAME * val, int n);
void print_brsfc_PHASE_OFF(FILE * fp, char *str, int indent, PHASE_OFF * val, int n);
void print_brsfc_RSP_PSC_INFO(FILE * fp, char *str, int indent, RSP_PSC_INFO * val, int n);
void print_brsfc_GIR_INFO(FILE * fp, char *str, int indent, GIR_INFO * val, int n);
void print_brsfc_ZY_EXPORT(FILE * fp, char *str, int indent, ZY_EXPORT * val, int n);
void print_brsfc_VIEWORDER_MODE_E(FILE * fp, char *str, int indent, VIEWORDER_MODE_E * val, int n);
void print_brsfc_REG_VIEWORDER_MODE_E(FILE * fp, char *str, int indent, REG_VIEWORDER_MODE_E * val, int n);
void print_brsfc_REGION_ORDER_MODE_E(FILE * fp, char *str, int indent, REGION_ORDER_MODE_E * val, int n);
void print_brsfc_CAL_PARAM(FILE * fp, char *str, int indent, CAL_PARAM * val, int n);
void print_brsfc_PARAM4D(FILE * fp, char *str, int indent, PARAM4D * val, int n);
void print_brsfc_SPIRAL_VIEW(FILE * fp, char *str, int indent, SPIRAL_VIEW * val, int n);
void print_brsfc_SLAB_OFF(FILE * fp, char *str, int indent, SLAB_OFF * val, int n);
void print_brsfc_CYLR_RF_TYPE_E(FILE * fp, char *str, int indent, CYLR_RF_TYPE_E * val, int n);
void print_brsfc_t_ktsamp(FILE * fp, char *str, int indent, t_ktsamp * val, int n);
void print_brsfc_ViewTable_kyz(FILE * fp, char *str, int indent, ViewTable_kyz * val, int n);
void print_brsfc_t_cgatetype(FILE * fp, char *str, int indent, t_cgatetype * val, int n);
void print_brsfc_t_fcineim(FILE * fp, char *str, int indent, t_fcineim * val, int n);
void print_brsfc_t_fcinent(FILE * fp, char *str, int indent, t_fcinent * val, int n);
void print_brsfc_cv_type(FILE * fp, char *str, int indent, cv_type * val, int n);
#ifdef __cplusplus
}
#endif

#endif
